[AMSDK-8709] - API to setting location permission level
adobe/places-monitor-android pull request #16
Opened 2019-09-30 17:19 UTC by PravinPK

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-10-04 19:47 UTC, sbenedicadb requested changes
a couple small code changes.  i'd like you to review some of the in-code docs w/ rekha for suggestions on how to make things better phrased.

2019-10-04 19:47 UTC, sbenedicadb commented on code/places-monitor-android/src/phone/java/com/adobe/marketing/mobile/PlacesActivity.java
> +	 * Checks if the permission to access fine location during app in use is granted.
`Checks if permission to access fine location while app is in use has been granted.`

2019-10-04 19:47 UTC, sbenedicadb commented on code/places-monitor-android/src/phone/java/com/adobe/marketing/mobile/PlacesActivity.java
> +	 * Checks if the permission to access fine location in background is granted.
`Checks if permission to access fine location while the app is in background has been granted.`

2019-10-04 19:47 UTC, sbenedicadb commented on code/places-monitor-android/src/phone/java/com/adobe/marketing/mobile/PlacesActivity.java
> +	public static void askPermission(PlacesMonitorLocationPermission locationPermission) {
`final` parameters please

2019-10-04 19:47 UTC, sbenedicadb commented on code/places-monitor-android/src/phone/java/com/adobe/marketing/mobile/PlacesLocationManager.java
> +				Log.debug(PlacesMonitorConstants.LOG_TAG, "Requesting while in use location permission");
debug log is wrong

2019-10-04 19:47 UTC, sbenedicadb commented on code/places-monitor-android/src/phone/java/com/adobe/marketing/mobile/PlacesLocationManager.java
> +								"Failed to start location updates, status code : SETTINGS_CHANGE_UNAVAILABLE");
i don't know what this means.

2019-10-07 20:52 UTC, PravinPK commented on code/places-monitor-android/src/phone/java/com/adobe/marketing/mobile/PlacesLocationManager.java
> +								"Failed to start location updates, status code : SETTINGS_CHANGE_UNAVAILABLE");
explained

2019-10-09 15:58 UTC, sbenedicadb approved these changes

2019-10-09 15:59 UTC, merged